version: '3'
services:
  postgresdb:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=nikhil382
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_service_db
    volumes:
      - database:/var/lib/postgresql/data

  auth-service:
    image: nikhil382/go-basic-grpc-auth-serivce
    environment:
      - SERVICE_PORT=:50051
      - DB_HOST=postgresdb
      - DB_NAME=auth_service_db
      - DB_USER=nikhil382
      - DB_PASSWORD=password
      - DB_PORT=5432  

    depends_on:
    - postgresdb

  pg-admin:
    image:  dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikhil@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  database:
    driver: local

